// Generated by CoffeeScript 1.7.1
(function() {
  Leap.plugin('networking', function(scope) {
    if (!scope.peer) {
      console.warn("No Peer supplied");
    }
    scope.connection = null;
    scope.sendFrames = false;
    scope.peer.on('error', function() {
      return console.log('peerjs error:', arguments);
    });
    scope.peer.on('connection', function(connection) {
      console.log('someone likes me', connection);
      scope.connection = connection;
      return scope.connectionEstablished();
    });
    scope.connect = function(id) {
      scope.connection = scope.peer.connect(id);
      return scope.connectionEstablished();
    };
    scope.connectionEstablished = function() {
      console.log('connection established', arguments);
      scope.sendFrames = true;
      return scope.connection.on('data', function(data) {
        return console.log('received:', data);
      });
    };
    return {
      beforeFrameCreated: function(frame) {
        if (!scope.sendFrames) {
          return;
        }
        console.log('send frame', frame.id);
        return scope.connection.send(frame.id);
      },
      afterFrameCreated: function(frame, rawFrameData) {}
    };
  });

}).call(this);
